// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASvTi7FZyls2dXnDsDxuPS21NDj2-ClgI',
    appId: '1:261967154396:web:360ee498b316dd7ffcb819',
    messagingSenderId: '261967154396',
    projectId: 'tickerwatch-983c4',
    authDomain: 'tickerwatch-983c4.firebaseapp.com',
    storageBucket: 'tickerwatch-983c4.appspot.com',
    measurementId: 'G-QXC6Z94G07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGA4EfPrQ_pQdSf73K4Le_6FNuYUcJu8',
    appId: '1:261967154396:android:03dec75a10eb731efcb819',
    messagingSenderId: '261967154396',
    projectId: 'tickerwatch-983c4',
    storageBucket: 'tickerwatch-983c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuub33o9EKfAmT_HvFKT5YQ1r-0Q2DcQ',
    appId: '1:261967154396:ios:0d64d5e1a0d0c2f9fcb819',
    messagingSenderId: '261967154396',
    projectId: 'tickerwatch-983c4',
    storageBucket: 'tickerwatch-983c4.appspot.com',
    iosBundleId: 'com.example.tickerwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuub33o9EKfAmT_HvFKT5YQ1r-0Q2DcQ',
    appId: '1:261967154396:ios:0d64d5e1a0d0c2f9fcb819',
    messagingSenderId: '261967154396',
    projectId: 'tickerwatch-983c4',
    storageBucket: 'tickerwatch-983c4.appspot.com',
    iosBundleId: 'com.example.tickerwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASvTi7FZyls2dXnDsDxuPS21NDj2-ClgI',
    appId: '1:261967154396:web:a42dcc259204d5affcb819',
    messagingSenderId: '261967154396',
    projectId: 'tickerwatch-983c4',
    authDomain: 'tickerwatch-983c4.firebaseapp.com',
    storageBucket: 'tickerwatch-983c4.appspot.com',
    measurementId: 'G-9NENKRZXJM',
  );
}
